name: pip_plugin
description: Flutter plugin for displaying customizable text overlays in Picture-in-Picture mode across all platforms.
version: 0.0.1+2

homepage: https://github.com/gyoussef55/pip_plugin
repository: https://github.com/gyoussef55/pip_plugin
issue_tracker: https://github.com/gyoussef55/pip_plugin/issues

topics:
  - flutter
  - picture-in-picture
  - pip

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  simple_pip_mode: ^1.1.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pip_plugin
        pluginClass: PipPlugin
      ios:
        pluginClass: PipPlugin
      linux:
        pluginClass: PipPlugin
      macos:
        pluginClass: PipPlugin
      windows:
        pluginClass: PipPluginCApi
      web:
        pluginClass: PipPluginWeb
        fileName: src/pip_plugin_web.dart
